### ISSUE TITLE
"Compact" sass options not allowed.

### ISSUE THREAD

**Issue by benja-admin** [secondnetwork/grunt-starter-kit#7]
Every time I clone I have to change the "compact" value in Gruntfile.js sass options to be "compressed" instead. Might be an error, might be my machine or dependencies but it is pretty consistent. What do you advise?

![Capture](https://user-images.githubusercontent.com/30055921/124043665-848e9700-d9d9-11eb-8868-662f39f937a6.PNG)

**Comment by secondnetwork** [comment]
I tested it on mac. everything work normal. have you update sass and nodejs to new version?
